# Generated by Django 4.2.23 on 2025-06-16 19:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('center', '0005_update_monthly_limits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mold', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='Firma Adı')),
                ('brand_name', models.CharField(blank=True, max_length=100, verbose_name='Marka Adı')),
                ('description', models.TextField(blank=True, verbose_name='Firma Açıklaması')),
                ('producer_type', models.CharField(choices=[('manufacturer', 'Kalıp Üreticisi'), ('laboratory', '3D Laboratuvar'), ('hybrid', 'Hibrit (Üretici + Lab)')], default='manufacturer', max_length=20, verbose_name='Üretici Türü')),
                ('address', models.TextField(verbose_name='Adres')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='İletişim E-posta')),
                ('website', models.URLField(blank=True, verbose_name='Web Sitesi')),
                ('tax_number', models.CharField(blank=True, max_length=20, verbose_name='Vergi Numarası')),
                ('trade_registry', models.CharField(blank=True, max_length=30, verbose_name='Ticaret Sicil No')),
                ('established_year', models.IntegerField(blank=True, null=True, verbose_name='Kuruluş Yılı')),
                ('mold_limit', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kalıp Limiti')),
                ('monthly_limit', models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Aylık Kalıp Limiti')),
                ('notification_preferences', models.CharField(default='system', max_length=200, verbose_name='Bildirim Tercihleri')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Doğrulanmış')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='Doğrulama Tarihi')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='producer_logos/', verbose_name='Logo')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='producer_certificates/', verbose_name='Sertifika')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Üretici Merkez',
                'verbose_name_plural': 'Üretici Merkezler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProducerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Sipariş No')),
                ('status', models.CharField(choices=[('received', 'Alındı'), ('designing', '3D Tasarım'), ('production', 'Üretimde'), ('quality_check', 'Kalite Kontrol'), ('packaging', 'Paketleme'), ('shipping', 'Kargoda'), ('delivered', 'Teslim Edildi'), ('cancelled', 'İptal Edildi')], default='received', max_length=20, verbose_name='Durum')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('normal', 'Normal'), ('high', 'Yüksek'), ('urgent', 'Acil')], default='normal', max_length=10, verbose_name='Öncelik')),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True, verbose_name='Tahmini Teslimat')),
                ('actual_delivery', models.DateTimeField(blank=True, null=True, verbose_name='Gerçek Teslimat')),
                ('shipping_company', models.CharField(blank=True, max_length=100, verbose_name='Kargo Şirketi')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Takip Numarası')),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kargo Ücreti')),
                ('producer_notes', models.TextField(blank=True, verbose_name='Üretici Notları')),
                ('center_notes', models.TextField(blank=True, verbose_name='Merkez Notları')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_orders', to='center.center')),
                ('ear_mold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_orders', to='mold.earmold')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='producer.producer')),
            ],
            options={
                'verbose_name': 'Üretici Siparişi',
                'verbose_name_plural': 'Üretici Siparişleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProducerProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('design_start', 'Tasarım Başladı'), ('design_complete', 'Tasarım Tamamlandı'), ('production_start', 'Üretim Başladı'), ('production_complete', 'Üretim Tamamlandı'), ('quality_start', 'Kalite Kontrol Başladı'), ('quality_complete', 'Kalite Kontrol Tamamlandı'), ('packaging_complete', 'Paketleme Tamamlandı'), ('shipping_start', 'Kargo Hazırlık'), ('shipped', 'Kargoya Verildi'), ('delivered', 'Teslim Edildi')], max_length=30, verbose_name='Aşama')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('operator', models.CharField(blank=True, max_length=100, verbose_name='Operatör')),
                ('duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='Süre (Dakika)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='production_logs/', verbose_name='Fotoğraf')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_logs', to='producer.producerorder')),
            ],
            options={
                'verbose_name': 'Üretim Logu',
                'verbose_name_plural': 'Üretim Logları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProducerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_is_producer', models.BooleanField(default=True, verbose_name='Gönderen Üretici mi?')),
                ('message_type', models.CharField(choices=[('order', 'Sipariş'), ('technical', 'Teknik'), ('administrative', 'İdari'), ('complaint', 'Şikayet'), ('general', 'Genel')], default='general', max_length=20, verbose_name='Mesaj Türü')),
                ('subject', models.CharField(max_length=200, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Arşivlendi')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Acil')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='producer_messages/', verbose_name='Ek Dosya')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderilme Tarihi')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Okunma Tarihi')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_messages', to='center.center')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='producer.producer')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='producer.producerorder')),
            ],
            options={
                'verbose_name': 'Üretici Mesajı',
                'verbose_name_plural': 'Üretici Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProducerNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('active', 'Aktif'), ('suspended', 'Askıya Alınmış'), ('terminated', 'Sonlandırılmış')], default='pending', max_length=20, verbose_name='Durum')),
                ('can_receive_orders', models.BooleanField(default=True, verbose_name='Sipariş Alabilir')),
                ('can_send_messages', models.BooleanField(default=True, verbose_name='Mesaj Gönderebilir')),
                ('priority_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Öncelik Seviyesi')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Katılma Tarihi')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Aktifleşme Tarihi')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='Son Aktivite')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_networks', to='center.center')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_centers', to='producer.producer')),
            ],
            options={
                'verbose_name': 'Üretici Ağı',
                'verbose_name_plural': 'Üretici Ağları',
                'ordering': ['-joined_at'],
                'unique_together': {('producer', 'center')},
            },
        ),
    ]
