# Generated by Django 4.2.23 on 2025-06-17 11:13

from django.db import migrations, models


def fix_duplicate_tax_numbers(apps, schema_editor):
    """Duplicate tax_number'ları düzelt"""
    Producer = apps.get_model('producer', 'Producer')
    
    # Tax number'ı boş olan producer'ları bul ve benzersiz değerler ata
    producers_without_tax = Producer.objects.filter(tax_number__isnull=True) | Producer.objects.filter(tax_number='')
    for i, producer in enumerate(producers_without_tax):
        producer.tax_number = f'TEMP-{producer.id}-{i}'
        producer.save()
    
    # Duplicate tax_number'ları bul ve düzelt
    seen_tax_numbers = set()
    duplicate_producers = []
    
    for producer in Producer.objects.all():
        if producer.tax_number in seen_tax_numbers:
            duplicate_producers.append(producer)
        else:
            seen_tax_numbers.add(producer.tax_number)
    
    # Duplicate'ları düzelt
    for i, producer in enumerate(duplicate_producers):
        producer.tax_number = f'DUP-{producer.id}-{i}'
        producer.save()


def reverse_fix_duplicate_tax_numbers(apps, schema_editor):
    """Reverse operation - gerekli değil"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='verification_date',
        ),
        migrations.AddField(
            model_name='producer',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='company_name',
            field=models.CharField(max_length=200, verbose_name='Firma Adı'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='mold_limit',
            field=models.PositiveIntegerField(default=100, verbose_name='Aylık Kalıp Limiti'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        # Önce duplicate'ları düzelt
        migrations.RunPython(fix_duplicate_tax_numbers, reverse_fix_duplicate_tax_numbers),
        # Sonra unique constraint ekle
        migrations.AlterField(
            model_name='producer',
            name='tax_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Vergi Numarası'),
        ),
    ]
