# Generated by Django 4.2.23 on 2025-06-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0002_remove_producer_verification_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Doğrulama Tarihi'),
        ),
    ]
