# Generated by Django 4.2.23 on 2025-06-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0003_producer_verification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='producernetwork',
            name='assignment_reason',
            field=models.TextField(blank=True, verbose_name='Atama Nedeni'),
        ),
        migrations.AddField(
            model_name='producernetwork',
            name='auto_assigned',
            field=models.BooleanField(default=False, verbose_name='Otomatik Atama'),
        ),
        migrations.AddField(
            model_name='producernetwork',
            name='terminated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sonlandırılma Tarihi'),
        ),
        migrations.AddField(
            model_name='producernetwork',
            name='termination_reason',
            field=models.TextField(blank=True, verbose_name='Sonlandırma Nedeni'),
        ),
    ]
