# Generated by Django 4.2.23 on 2025-06-27 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0004_producernetwork_assignment_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='mold_limit',
        ),
        migrations.DeleteModel(
            name='ProducerMessage',
        ),
    ]
