# Generated by Django 4.2.23 on 2025-10-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0005_remove_producer_mold_limit_delete_producermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Bu sipariş için üreticiye ödenecek toplam tutar', max_digits=10, verbose_name='Sipariş Tutarı'),
        ),
    ]
