# Generated by Django 4.2.23 on 2025-06-18 13:53
# Performance optimization migration - Database indexes

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('mold', '0002_revision_revision_type'),
        ('producer', '0002_remove_producer_verification_date_and_more'),
        ('center', '0005_update_monthly_limits'),
    ]

    operations = [
        # EarMold tablosu için performans index'leri
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_earmold_status_created ON mold_earmold(status, created_at DESC);",
            reverse_sql="DROP INDEX IF EXISTS idx_earmold_status_created;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_earmold_center_status ON mold_earmold(center_id, status);",
            reverse_sql="DROP INDEX IF EXISTS idx_earmold_center_status;"
        ),
        
        # ProducerOrder tablosu için performans index'leri
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_producer_order_status_priority ON producer_producerorder(status, priority);",
            reverse_sql="DROP INDEX IF EXISTS idx_producer_order_status_priority;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_producer_order_delivery ON producer_producerorder(estimated_delivery) WHERE status IN ('received', 'designing', 'production', 'quality_check');",
            reverse_sql="DROP INDEX IF EXISTS idx_producer_order_delivery;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_producer_order_created_status ON producer_producerorder(created_at DESC, status);",
            reverse_sql="DROP INDEX IF EXISTS idx_producer_order_created_status;"
        ),
        
        # Producer tablosu için index'ler
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_producer_active_verified ON producer_producer(is_active, is_verified);",
            reverse_sql="DROP INDEX IF EXISTS idx_producer_active_verified;"
        ),
        
        # ProducerNetwork tablosu için index'ler
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_producer_network_status ON producer_producernetwork(status);",
            reverse_sql="DROP INDEX IF EXISTS idx_producer_network_status;"
        ),
        
        # User tablosu için last_login index'i
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_auth_user_last_login ON auth_user(last_login DESC) WHERE last_login IS NOT NULL;",
            reverse_sql="DROP INDEX IF EXISTS idx_auth_user_last_login;"
        ),
        
        # Composite index'ler - sık kullanılan sorgular için
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_mold_center_created ON mold_earmold(center_id, created_at DESC);",
            reverse_sql="DROP INDEX IF EXISTS idx_mold_center_created;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_order_producer_status ON producer_producerorder(producer_id, status);",
            reverse_sql="DROP INDEX IF EXISTS idx_order_producer_status;"
        ),
    ]
