# Generated by Django 4.2.23 on 2025-06-18 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20250618_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('center_to_admin', 'Merkez → Admin'), ('producer_to_admin', 'Üretici → Admin'), ('admin_to_center', 'Admin → Merkez'), ('admin_to_producer', 'Admin → Üretici'), ('admin_broadcast', 'Admin → Toplu Duyuru')], max_length=20, verbose_name='Mesaj Türü')),
                ('subject', models.CharField(max_length=200, verbose_name='Konu')),
                ('content', models.TextField(verbose_name='Mesaj İçeriği')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('normal', 'Normal'), ('high', 'Yüksek'), ('urgent', 'Acil')], default='normal', max_length=10, verbose_name='Öncelik')),
                ('is_broadcast', models.BooleanField(default=False, verbose_name='Toplu Mesaj')),
                ('broadcast_to_centers', models.BooleanField(default=False, verbose_name='İşitme Merkezlerine')),
                ('broadcast_to_producers', models.BooleanField(default=False, verbose_name='Üretici Merkezlere')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Arşivlendi')),
                ('is_replied', models.BooleanField(default=False, verbose_name='Cevaplandı')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='message_attachments/', verbose_name='Ek Dosya')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderilme Tarihi')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Okunma Tarihi')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Cevaplandığı Tarih')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.message', verbose_name='Cevaplanan Mesaj')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Mesajlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Okundu'),
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Okunma Tarihi')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='core.message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mesaj Alıcısı',
                'verbose_name_plural': 'Mesaj Alıcıları',
                'unique_together': {('message', 'recipient')},
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='core_messag_sender__43db24_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'is_read'], name='core_messag_recipie_ffa7b4_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type', 'created_at'], name='core_messag_message_6f9f93_idx'),
        ),
    ]
