# Generated by Django 4.2.23 on 2025-06-21 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_message_contactmessage_is_read_messagerecipient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Plan Adı')),
                ('plan_type', models.CharField(choices=[('pay_per_use', 'Kullandıkça Öde'), ('center_basic', 'İşitme Merkezi - Temel'), ('center_professional', 'İşitme Merkezi - Profesyonel'), ('producer', 'Üretici Merkez')], max_length=20, unique=True, verbose_name='Plan Türü')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat (USD)')),
                ('price_try', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat (TL)')),
                ('monthly_model_limit', models.IntegerField(blank=True, help_text='Null ise sınırsız', null=True, verbose_name='Aylık Model Limiti')),
                ('is_monthly', models.BooleanField(default=True, verbose_name='Aylık Plan')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='Özellikler')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Fiyatlandırma Planı',
                'verbose_name_plural': 'Fiyatlandırma Planları',
                'ordering': ['price_usd'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('expired', 'Süresi Dolmuş'), ('cancelled', 'İptal Edilmiş'), ('pending', 'Beklemede')], default='active', max_length=10, verbose_name='Durum')),
                ('models_used_this_month', models.IntegerField(default=0, verbose_name='Bu Ay Kullanılan Model Sayısı')),
                ('last_reset_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Son Sıfırlama Tarihi')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ödenen Tutar')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('TRY', 'TRY')], default='USD', max_length=3, verbose_name='Para Birimi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.pricingplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Aboneliği',
                'verbose_name_plural': 'Kullanıcı Abonelikleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('TRY', 'TRY')], max_length=3, verbose_name='Para Birimi')),
                ('payment_type', models.CharField(choices=[('subscription', 'Abonelik'), ('pay_per_use', 'Kullandıkça Öde')], max_length=15, verbose_name='Ödeme Türü')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız'), ('refunded', 'İade Edildi')], default='pending', max_length=10, verbose_name='Durum')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Ödeme Yöntemi')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='İşlem ID')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.usersubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ödeme Geçmişi',
                'verbose_name_plural': 'Ödeme Geçmişleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
