# Generated by Django 4.2.23 on 2025-06-26 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_pricingplan_usersubscription_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerecipient',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Arşivlendi'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='messagerecipient',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Alıcı'),
        ),
        migrations.CreateModel(
            name='SimpleNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('message', models.TextField(max_length=500, verbose_name='Mesaj')),
                ('notification_type', models.CharField(choices=[('info', 'Bilgi'), ('success', 'Başarılı'), ('warning', 'Uyarı'), ('error', 'Hata'), ('system', 'Sistem'), ('order', 'Sipariş'), ('message', 'Mesaj')], default='info', max_length=20, verbose_name='Tür')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Okunma Tarihi')),
                ('related_url', models.URLField(blank=True, null=True, verbose_name='İlgili Link')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='İlgili Obje ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Basit Bildirim',
                'verbose_name_plural': 'Basit Bildirimler',
                'ordering': ['-created_at'],
            },
        ),
    ]
