# Generated by Django 4.2.23 on 2025-07-02 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_pricingplan_plan_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=10, verbose_name='Durum')),
                ('user_notes', models.TextField(blank=True, help_text='Talep ile ilgili özel notlarınız', verbose_name='Kullanıcı Notları')),
                ('admin_notes', models.TextField(blank=True, help_text='Admin tarafından eklenen notlar', verbose_name='Admin Notları')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Talep Tarihi')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='İşlenme Tarihi')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.pricingplan', verbose_name='Talep Edilen Plan')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_subscription_requests', to=settings.AUTH_USER_MODEL, verbose_name='İşleyen Admin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Abonelik Talebi',
                'verbose_name_plural': 'Abonelik Talepleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
