# Generated by Django 4.2.23 on 2025-07-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_subscriptionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='plan_type',
            field=models.CharField(choices=[('trial', 'Ücretsiz Deneme'), ('pay_per_use', 'Kullandıkça Öde'), ('center_basic', 'İşitme Merkezi - Temel'), ('center_professional', 'İşitme Merkezi - Profesyonel'), ('producer', 'Üretici Merkez'), ('enterprise', 'Kurumsal')], max_length=20, unique=True, verbose_name='Plan Türü'),
        ),
    ]
