# Generated by Django 4.2.23 on 2025-08-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_pricingplan_plan_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingplan',
            options={'ordering': ['order', 'price_usd'], 'verbose_name': 'Fiyatlandırma Planı', 'verbose_name_plural': 'Fiyatlandırma Planları'},
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='badge_text',
            field=models.CharField(blank=True, help_text='Örn: YENİ, POPÜLER', max_length=50, null=True, verbose_name='Rozet Metni'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Öne Çıkan'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='order',
            field=models.IntegerField(default=0, help_text='Küçük değer önce gösterilir', verbose_name='Sıralama'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='trial_days',
            field=models.IntegerField(default=0, help_text='0 ise deneme süresi yok', verbose_name='Deneme Süresi (Gün)'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='plan_type',
            field=models.CharField(choices=[('trial', 'Ücretsiz Deneme'), ('producer_trial', 'Üretici - Ücretsiz Deneme'), ('pay_per_use', 'Kullandıkça Öde'), ('center_basic', 'İşitme Merkezi - Temel'), ('center_professional', 'İşitme Merkezi - Profesyonel'), ('producer', 'Üretici Merkez'), ('enterprise', 'Kurumsal')], max_length=20, verbose_name='Plan Türü'),
        ),
    ]
