# Generated by Django 4.2.23 on 2025-10-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_campaign_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='monthly_fee_try',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Aylık Sistem Kullanım Bedeli (TL)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='per_mold_price_try',
            field=models.DecimalField(decimal_places=2, default=450.0, max_digits=10, verbose_name='Kalıp Başına Ücret (TL)'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Ödeme Tarihi'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='models_used_total',
            field=models.IntegerField(default=0, verbose_name='Toplam Kullanılan Model Sayısı'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='monthly_fee_paid',
            field=models.BooleanField(default=False, verbose_name='Bu Ay Aylık Ücret Ödendi'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='total_mold_cost_this_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bu Ay Kalıp Maliyeti'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='plan_type',
            field=models.CharField(choices=[('standard', 'Standart Paket')], default='standard', max_length=20, verbose_name='Plan Türü'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='price_try',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Fiyat (TL)'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fiyat (USD)'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('TRY', 'TRY')], default='TRY', max_length=3, verbose_name='Para Birimi'),
        ),
    ]
