# Generated by Django 4.2.23 on 2025-10-07 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_update_pricing_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='modeling_service_fee_try',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='Modeleme Hizmeti Ücreti (TL)'),
        ),
        migrations.CreateModel(
            name='FinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Yıl')),
                ('month', models.IntegerField(verbose_name='Ay')),
                ('center_monthly_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Aylık Sistem Ücretleri')),
                ('center_mold_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kalıp Gelirleri')),
                ('center_modeling_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Modeleme Gelirleri')),
                ('center_total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Merkez Toplam Gelir')),
                ('producer_gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Üretici Brüt Gelir')),
                ('moldpark_commission_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='MoldPark Komisyon Geliri')),
                ('producer_net_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Üretici Net Gelir')),
                ('total_credit_card_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Toplam KK Komisyonu')),
                ('total_gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Toplam Brüt Gelir')),
                ('total_net_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Toplam Net Gelir')),
                ('total_centers', models.IntegerField(default=0, verbose_name='Toplam Merkez Sayısı')),
                ('total_producers', models.IntegerField(default=0, verbose_name='Toplam Üretici Sayısı')),
                ('total_molds', models.IntegerField(default=0, verbose_name='Toplam Kalıp Sayısı')),
                ('total_modelings', models.IntegerField(default=0, verbose_name='Toplam Modeleme Sayısı')),
                ('total_invoices', models.IntegerField(default=0, verbose_name='Toplam Fatura Sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
            ],
            options={
                'verbose_name': 'Mali Özet',
                'verbose_name_plural': 'Mali Özetler',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Fatura No')),
                ('invoice_type', models.CharField(choices=[('center', 'İşitme Merkezi Faturası'), ('producer', 'Üretici Merkez Faturası')], max_length=20, verbose_name='Fatura Türü')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Kesim Tarihi')),
                ('due_date', models.DateField(verbose_name='Vade Tarihi')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ödeme Tarihi')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ara Toplam')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Aylık Sistem Ücreti')),
                ('mold_count', models.IntegerField(default=0, verbose_name='Kalıp Sayısı')),
                ('mold_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kalıp Maliyeti')),
                ('modeling_count', models.IntegerField(default=0, verbose_name='Modeleme Sayısı')),
                ('modeling_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Modeleme Maliyeti')),
                ('producer_order_count', models.IntegerField(default=0, verbose_name='Sipariş Sayısı')),
                ('producer_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Üretici Geliri')),
                ('moldpark_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='MoldPark Komisyonu (%6.5)')),
                ('credit_card_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kredi Kartı Komisyonu (%2.6)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toplam Tutar')),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Net Tutar (Komisyon Sonrası)')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('issued', 'Kesildi'), ('paid', 'Ödendi'), ('overdue', 'Vadesi Geçmiş'), ('cancelled', 'İptal Edildi')], default='draft', max_length=20, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturalar',
                'ordering': ['-issue_date', '-created_at'],
                'indexes': [models.Index(fields=['invoice_number'], name='core_invoic_invoice_aef6bc_idx'), models.Index(fields=['user', 'status'], name='core_invoic_user_id_8efa39_idx'), models.Index(fields=['issue_date'], name='core_invoic_issue_d_99a2a6_idx')],
            },
        ),
    ]
