# Generated by Django 4.2.23 on 2025-10-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_invoice_financial_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='digital_scan_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Digital Tarama Maliyeti'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='digital_scan_count',
            field=models.IntegerField(default=0, verbose_name='Digital Tarama Sayısı'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='physical_mold_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fiziksel Kalıp Maliyeti'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='physical_mold_count',
            field=models.IntegerField(default=0, verbose_name='Fiziksel Kalıp Sayısı'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='modeling_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Modeleme Maliyeti (Eski)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='modeling_count',
            field=models.IntegerField(default=0, verbose_name='Modeleme Sayısı (Eski)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='mold_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kalıp Maliyeti (Eski)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='mold_count',
            field=models.IntegerField(default=0, verbose_name='Kalıp Sayısı (Eski)'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='modeling_service_fee_try',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='Digital Tarama Hizmeti Ücreti (TL)'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='per_mold_price_try',
            field=models.DecimalField(decimal_places=2, default=450.0, max_digits=10, verbose_name='Fiziksel Kalıp Gönderme Ücreti (TL)'),
        ),
    ]
