# Generated by Django 4.2.23 on 2025-10-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_update_invoice_field_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='digital_scans_this_month',
            field=models.IntegerField(default=0, verbose_name='Bu Ay Digital Tarama Sayısı'),
        ),
    ]
