# Generated by Django 4.2.23 on 2025-10-09 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0006_producerorder_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_add_digital_scans_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='moldpark_commission',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='producer_revenue',
        ),
        migrations.AddField(
            model_name='invoice',
            name='breakdown_data',
            field=models.JSONField(blank=True, default=dict, help_text='Faturadaki her işlem için detaylı kırılım bilgileri', verbose_name='İşlem Kırılımları'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Faturayı Kesén'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='moldpark_system_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='MoldPark Sistem Ücreti (%6.5)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='producer.producer', verbose_name='Üretici'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='producer_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Üretici Komisyonu Kesintisi'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='producer_gross_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Üretici Brüt Geliri'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='producer_net_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Üretici Net Geliri'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gönderilme Tarihi'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toplam Kesintiler'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('center_monthly', 'İşitme Merkezi - Aylık Fatura'), ('center_pay_per_use', 'İşitme Merkezi - Kullandıkça Öde'), ('producer_monthly', 'Üretici - Aylık Kazanç Faturası'), ('producer_payment', 'Üretici - Ödeme Faturası')], max_length=20, verbose_name='Fatura Türü'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Net Ödenecek Tutar'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='producer_order_count',
            field=models.IntegerField(default=0, verbose_name='Tamamlanan Sipariş Sayısı'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('issued', 'Kesildi'), ('sent', 'Gönderildi'), ('paid', 'Ödendi'), ('overdue', 'Vadesi Geçmiş'), ('cancelled', 'İptal Edildi'), ('refunded', 'İade Edildi')], default='draft', max_length=20, verbose_name='Durum'),
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('moldpark_fee', 'MoldPark Sistem Ücreti (%6.5)'), ('credit_card', 'Kredi Kartı Komisyonu (%2.6)'), ('producer_commission', 'Üretici Komisyonu')], max_length=20, verbose_name='Komisyon Türü')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Yüzde')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='core.invoice', verbose_name='Fatura')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='producer.producer', verbose_name='Üretici')),
            ],
            options={
                'verbose_name': 'Komisyon',
                'verbose_name_plural': 'Komisyonlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('center_monthly_fee', 'İşitme Merkezi - Aylık Sistem Ücreti'), ('center_physical_mold', 'İşitme Merkezi - Fiziksel Kalıp'), ('center_digital_scan', 'İşitme Merkezi - Dijital Tarama'), ('producer_payment', 'Üretici - Ödeme Alımı'), ('producer_commission', 'Üretici - Komisyon Kesintisi'), ('moldpark_commission', 'MoldPark - Sistem Komisyonu'), ('moldpark_credit_card_fee', 'MoldPark - KK Komisyonu')], max_length=25, verbose_name='İşlem Türü')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('currency', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD')], default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız'), ('cancelled', 'İptal Edildi')], default='pending', max_length=10, verbose_name='Durum')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('reference_id', models.CharField(blank=True, help_text='Sipariş ID, kalıp ID vb.', max_length=100, verbose_name='Referans ID')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Ödeme Yöntemi')),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='İşlem Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.invoice', verbose_name='İlgili Fatura')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='producer.producer', verbose_name='Üretici')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'İşlem',
                'verbose_name_plural': 'İşlemler',
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['transaction_type', 'status'], name='core_transa_transac_348285_idx'), models.Index(fields=['user', 'transaction_date'], name='core_transa_user_id_8272c7_idx'), models.Index(fields=['producer', 'transaction_date'], name='core_transa_produce_b0b579_idx')],
            },
        ),
    ]
