# Generated by Django 4.2.23 on 2025-10-10 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0006_producerorder_price'),
        ('mold', '0013_alter_earmold_status'),
        ('center', '0007_delete_centermessage'),
        ('core', '0014_remove_invoice_moldpark_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='credit_card_fee_rate',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=5, verbose_name='Kredi Kartı Komisyonu Oranı (%)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issued_by_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_invoices', to='center.center', verbose_name='Faturayı Kesén Merkez'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issued_by_producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_invoices', to='producer.producer', verbose_name='Faturayı Kesén Üretici'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='moldpark_service_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='MoldPark Hizmet Bedeli'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='moldpark_service_fee_rate',
            field=models.DecimalField(decimal_places=2, default=6.5, max_digits=5, verbose_name='MoldPark Hizmet Bedeli Oranı (%)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='physical_mold_unit_price',
            field=models.DecimalField(decimal_places=2, default=450.0, max_digits=10, verbose_name='Fiziksel Kalıp Birim Fiyat'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_destination',
            field=models.CharField(blank=True, help_text='Bu tutarın nereye gideceği', max_length=200, verbose_name='Tutar Hedefi'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_source',
            field=models.CharField(blank=True, help_text='Bu tutarın nereden geldiği', max_length=200, verbose_name='Tutar Kaynağı'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='center.center', verbose_name='İlgili Merkez'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='credit_card_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bu işlemden kesilen KK komisyonu', max_digits=10, verbose_name='KK Komisyonu'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ear_mold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='mold.earmold', verbose_name='İlgili Kalıp'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='moldpark_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Bu işlemden MoldPark'ın aldığı ücret", max_digits=10, verbose_name='MoldPark Ücreti'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='service_provider',
            field=models.CharField(blank=True, help_text='Hangi kurum/kişi hizmeti verdi', max_length=100, verbose_name='Hizmet Veren'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='service_type',
            field=models.CharField(blank=True, help_text='Hizmet kategorisi', max_length=100, verbose_name='Hizmet Türü'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('center_admin_invoice', 'İşitme Merkezi - Kalıp Gönderim Faturası'), ('producer_invoice', 'Üretici - Hizmet Bedeli Faturası'), ('center_monthly', 'İşitme Merkezi - Aylık Sistem Faturası'), ('producer_monthly', 'Üretici - Aylık Kazanç Faturası'), ('producer_payment', 'Üretici - Ödeme Faturası')], max_length=20, verbose_name='Fatura Türü'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('center_monthly_fee', 'İşitme Merkezi - Aylık Sistem Ücreti'), ('center_physical_mold', 'İşitme Merkezi - Fiziksel Kalıp'), ('center_digital_scan', 'İşitme Merkezi - Dijital Tarama'), ('center_invoice_payment', 'İşitme Merkezi - Fatura Ödemesi'), ('producer_payment', 'Üretici - Ödeme Alımı'), ('producer_commission', 'Üretici - Komisyon Kesintisi'), ('producer_invoice_payment', 'Üretici - Fatura Ödemesi'), ('moldpark_commission', 'MoldPark - Sistem Komisyonu'), ('moldpark_credit_card_fee', 'MoldPark - KK Komisyonu'), ('moldpark_collection', 'MoldPark - Tahsilat'), ('moldpark_payment', 'MoldPark - Ödeme')], max_length=25, verbose_name='İşlem Türü'),
        ),
    ]
