# Generated by Django 4.2.23 on 2025-10-11 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_add_vat_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Örn: 2025 Standart Fiyatlandırma', max_length=100, verbose_name='Fiyatlandırma Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('physical_mold_price', models.DecimalField(decimal_places=2, default=450.0, help_text='KDV dahil fiziksel kalıp üretim fiyatı', max_digits=10, verbose_name='Fiziksel Kalıp Fiyatı (₺)')),
                ('digital_modeling_price', models.DecimalField(decimal_places=2, default=50.0, help_text='KDV dahil 3D modelleme hizmet fiyatı', max_digits=10, verbose_name='3D Modelleme Fiyatı (₺)')),
                ('monthly_system_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='İşitme merkezleri için aylık sabit ücret (şu an kullanılmıyor)', max_digits=10, verbose_name='Aylık Sistem Kullanım Ücreti (₺)')),
                ('moldpark_commission_rate', models.DecimalField(decimal_places=2, default=6.5, help_text='MoldPark komisyon oranı (örn: 6.50 = %6.5)', max_digits=5, verbose_name='MoldPark Hizmet Bedeli Oranı (%)')),
                ('credit_card_commission_rate', models.DecimalField(decimal_places=2, default=3.0, help_text='Kredi kartı işlem komisyonu (örn: 3.00 = %3)', max_digits=5, verbose_name='Kredi Kartı Komisyon Oranı (%)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20.0, help_text='Katma Değer Vergisi oranı (örn: 20.00 = %20)', max_digits=5, verbose_name='KDV Oranı (%)')),
                ('is_active', models.BooleanField(default=False, help_text='Sistemde aktif kullanılan fiyatlandırma (sadece bir tane aktif olabilir)', verbose_name='Aktif')),
                ('effective_date', models.DateField(default=django.utils.timezone.now, help_text='Bu fiyatların geçerli olduğu tarih', verbose_name='Geçerlilik Başlangıç Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pricings', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Fiyatlandırma Yapılandırması',
                'verbose_name_plural': 'Fiyatlandırma Yapılandırmaları',
                'ordering': ['-effective_date', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'effective_date'], name='core_pricin_is_acti_d8f03c_idx')],
            },
        ),
    ]
