# Generated by Django 4.2.23 on 2025-11-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_pricingconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfiguration',
            name='digital_modeling_price',
            field=models.DecimalField(decimal_places=2, default=19.0, help_text='KDV dahil 3D modelleme hizmet fiyatı', max_digits=10, verbose_name='3D Modelleme Fiyatı (₺)'),
        ),
        migrations.AlterField(
            model_name='pricingconfiguration',
            name='monthly_system_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='İşitme merkezleri için aylık sabit ücret (0,00 TL = Ücretsiz)', max_digits=10, verbose_name='Aylık Sistem Kullanım Ücreti (₺)'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='plan_type',
            field=models.CharField(choices=[('standard', 'Standart Paket'), ('package', 'Kalıp Paketi'), ('single', 'Tek Kalıp')], default='standard', max_length=20, verbose_name='Plan Türü'),
        ),
    ]
