# Generated by Django 4.2.23 on 2025-11-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_update_pricing_plan_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='package_credits',
            field=models.IntegerField(default=0, help_text='Satın alınan paketten kalan kullanım hakları', verbose_name='Paket Kullanım Hakları'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='used_credits',
            field=models.IntegerField(default=0, help_text='Paket haklarından kullanılan miktar', verbose_name='Kullanılan Haklar'),
        ),
    ]
