# Generated by Django 4.2.23 on 2025-11-10 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_add_package_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='package_credits',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='used_credits',
        ),
        migrations.CreateModel(
            name='PurchasedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Satın Alma Tarihi')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Satın alındığı andaki paket fiyatı', max_digits=10, verbose_name='Satın Alınan Fiyat')),
                ('total_credits', models.IntegerField(help_text='Paketin içindeki kalıp sayısı', verbose_name='Toplam Paket Hakkı')),
                ('used_credits', models.IntegerField(default=0, help_text='Paket haklarından kullanılan miktar', verbose_name='Kullanılan Haklar')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('completed', 'Tamamlandı - Tüm Haklar Kullanıldı'), ('expired', 'Süresi Dolmuş'), ('cancelled', 'İptal Edildi')], default='active', max_length=20, verbose_name='Durum')),
                ('completion_date', models.DateTimeField(blank=True, help_text='Tüm haklar tüketildiğinde', null=True, verbose_name='Tamamlama Tarihi')),
                ('moldpark_commission', models.DecimalField(decimal_places=2, default=0, help_text='Otomatik hesaplanır', max_digits=10, verbose_name='MoldPark Komisyonu (%6.5)')),
                ('producer_payment', models.DecimalField(decimal_places=2, default=0, help_text='Fiyat - Komisyon', max_digits=10, verbose_name='Üretici Ödemesi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('package', models.ForeignKey(limit_choices_to={'plan_type': 'package'}, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='core.pricingplan', verbose_name='Paket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_packages', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Satın Alınan Paket',
                'verbose_name_plural': 'Satın Alınan Paketler',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
