# Generated by Django 4.2.23 on 2025-11-16 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_package_credits'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageRecipient',
        ),
    ]
