# Generated by Django 4.2.23 on 2025-11-10 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_remove_usersubscription_package_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedpackage',
            name='payment_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_package', to='core.paymenthistory', verbose_name='Ödeme Kaydı'),
        ),
        migrations.AddField(
            model_name='purchasedpackage',
            name='producer_payment_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ödeme Onay Tarihi'),
        ),
        migrations.AddField(
            model_name='purchasedpackage',
            name='producer_payment_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchased_packages', to=settings.AUTH_USER_MODEL, verbose_name='Ödemeyi Onaylayan Admin'),
        ),
        migrations.AddField(
            model_name='purchasedpackage',
            name='producer_payment_notes',
            field=models.TextField(blank=True, verbose_name='Üretici Ödeme Notları'),
        ),
        migrations.AddField(
            model_name='purchasedpackage',
            name='producer_payment_paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Üretici Ödeme Tarihi'),
        ),
        migrations.AddField(
            model_name='purchasedpackage',
            name='producer_payment_status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('paid', 'Ödendi')], default='pending', max_length=10, verbose_name='Üretici Ödeme Durumu'),
        ),
    ]
