# Generated by Django 4.2.23 on 2025-11-20 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_delete_messagerecipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransferConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Banka Adı')),
                ('account_holder', models.CharField(max_length=100, verbose_name='Hesap Sahibi')),
                ('iban', models.CharField(max_length=34, unique=True, verbose_name='IBAN')),
                ('swift_code', models.CharField(blank=True, max_length=11, verbose_name='SWIFT Kodu')),
                ('branch_code', models.CharField(blank=True, max_length=10, verbose_name='Şube Kodu')),
                ('account_number', models.CharField(blank=True, max_length=20, verbose_name='Hesap Numarası')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
            ],
            options={
                'verbose_name': 'Havale Bilgileri',
                'verbose_name_plural': 'Havale Bilgileri',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('credit_card', 'Kredi Kartı'), ('bank_transfer', 'Havale/EFT')], max_length=20, verbose_name='Ödeme Türü')),
                ('name', models.CharField(max_length=100, verbose_name='Ödeme Yöntemi Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('bank_transfer_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_methods', to='core.banktransferconfiguration')),
            ],
            options={
                'verbose_name': 'Ödeme Yöntemi',
                'verbose_name_plural': 'Ödeme Yöntemleri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('currency', models.CharField(choices=[('TRY', 'TRY')], default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('confirmed', 'Onaylandı'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız'), ('refunded', 'İade Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='payment_receipts/', verbose_name='Ödeme Makbuzu')),
                ('bank_confirmation_number', models.CharField(blank=True, max_length=50, verbose_name='Banka Referans No')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ödeme Tarihi')),
                ('last_four_digits', models.CharField(blank=True, max_length=4, verbose_name='Kartın Son 4 Hanesi')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='İşlem ID')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notları')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay Tarihi')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.invoice', verbose_name='Fatura')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.paymentmethod', verbose_name='Ödeme Yöntemi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_payments', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
                'ordering': ['-created_at'],
            },
        ),
    ]
