# Generated by Django 4.2.23 on 2025-12-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_banktransferconfiguration_paymentmethod_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='commission_type',
            field=models.CharField(choices=[('moldpark_fee', 'MoldPark Sistem Ücreti (%7.5)'), ('credit_card', 'Kredi Kartı Komisyonu (%2.6)'), ('producer_commission', 'Üretici Komisyonu')], max_length=20, verbose_name='Komisyon Türü'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='moldpark_service_fee_rate',
            field=models.DecimalField(decimal_places=2, default=7.5, max_digits=5, verbose_name='MoldPark Hizmet Bedeli Oranı (%)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='moldpark_system_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='MoldPark Sistem Ücreti (%7.5)'),
        ),
        migrations.AlterField(
            model_name='pricingconfiguration',
            name='moldpark_commission_rate',
            field=models.DecimalField(decimal_places=2, default=7.5, help_text='MoldPark komisyon oranı (örn: 7.50 = %7.5)', max_digits=5, verbose_name='MoldPark Hizmet Bedeli Oranı (%)'),
        ),
    ]
