# Generated by Django 4.2.23 on 2025-11-10 13:50

from django.db import migrations, models


def set_monthly_fee_zero(apps, schema_editor):
    PricingPlan = apps.get_model('core', 'PricingPlan')
    PricingPlan.objects.all().update(monthly_fee_try=0)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_purchasedpackage_payment_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='monthly_fee_try',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Aylık Sistem Kullanım Bedeli (TL)'),
        ),
        migrations.RunPython(set_monthly_fee_zero, reverse_code=noop),
    ]
