# Generated by Django 4.2.23 on 2025-12-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_update_moldpark_commission_rate_to_7_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='iyzico_conversation_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='İyzico Konuşma ID'),
        ),
        migrations.AddField(
            model_name='payment',
            name='iyzico_payment_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='İyzico Ödeme ID'),
        ),
        migrations.AddField(
            model_name='payment',
            name='iyzico_response',
            field=models.JSONField(blank=True, null=True, verbose_name='İyzico Yanıt'),
        ),
        migrations.AddField(
            model_name='payment',
            name='iyzico_token',
            field=models.CharField(blank=True, max_length=200, verbose_name='İyzico Token'),
        ),
    ]
