# Generated by Django 4.2.23 on 2025-12-08 11:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_iyzico_payment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('aras', 'Aras Kargo'), ('mng', 'MNG Kargo'), ('yurtici', 'Yurtiçi Kargo'), ('ptt', 'PTT Kargo'), ('surat', 'Sürat Kargo'), ('ups', 'UPS'), ('dhl', 'DHL'), ('other', 'Diğer')], max_length=100, verbose_name='Firma Adı')),
                ('display_name', models.CharField(max_length=100, verbose_name='Görünen Ad')),
                ('logo_url', models.URLField(blank=True, verbose_name='Logo URL')),
                ('website', models.URLField(blank=True, verbose_name='Web Sitesi')),
                ('api_enabled', models.BooleanField(default=False, verbose_name='API Aktif')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='API Anahtarı')),
                ('api_secret', models.CharField(blank=True, max_length=255, verbose_name='API Gizli Anahtar')),
                ('api_base_url', models.URLField(blank=True, verbose_name='API Base URL')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Temel Ücret')),
                ('kg_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='KG Başına Ücret')),
                ('estimated_delivery_days', models.IntegerField(default=1, verbose_name='Tahmini Teslimat Süresi (Gün)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
            ],
            options={
                'verbose_name': 'Kargo Firması',
                'verbose_name_plural': 'Kargo Firmaları',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='CargoShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Takip Numarası')),
                ('sender_name', models.CharField(max_length=100, verbose_name='Gönderen Adı')),
                ('sender_address', models.TextField(verbose_name='Gönderen Adresi')),
                ('sender_phone', models.CharField(max_length=20, verbose_name='Gönderen Telefon')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='Alıcı Adı')),
                ('recipient_address', models.TextField(verbose_name='Alıcı Adresi')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='Alıcı Telefon')),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0.5, max_digits=6, verbose_name='Ağırlık (KG)')),
                ('package_count', models.IntegerField(default=1, verbose_name='Paket Adedi')),
                ('description', models.TextField(blank=True, verbose_name='İçerik Açıklaması')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kargo Ücreti')),
                ('declared_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Beyan Değeri')),
                ('status', models.CharField(choices=[('pending', 'Hazırlanıyor'), ('picked_up', 'Alındı'), ('in_transit', 'Yolda'), ('out_for_delivery', 'Dağıtıma Çıktı'), ('delivered', 'Teslim Edildi'), ('returned', 'İade Edildi'), ('cancelled', 'İptal Edildi'), ('failed', 'Teslim Edilemedi')], default='pending', max_length=20, verbose_name='Durum')),
                ('status_description', models.TextField(blank=True, verbose_name='Durum Açıklaması')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Gönderilme Tarihi')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Teslim Tarihi')),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True, verbose_name='Tahmini Teslimat')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('api_response', models.JSONField(blank=True, null=True, verbose_name='API Yanıt')),
                ('cargo_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='core.cargocompany', verbose_name='Kargo Firması')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_shipments', to='core.invoice', verbose_name='Fatura')),
            ],
            options={
                'verbose_name': 'Kargo Gönderisi',
                'verbose_name_plural': 'Kargo Gönderileri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CargoTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Hazırlanıyor'), ('picked_up', 'Alındı'), ('in_transit', 'Yolda'), ('out_for_delivery', 'Dağıtıma Çıktı'), ('delivered', 'Teslim Edildi'), ('returned', 'İade Edildi'), ('cancelled', 'İptal Edildi'), ('failed', 'Teslim Edilemedi')], max_length=20, verbose_name='Durum')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Konum')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='Ham Veri')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='core.cargoshipment', verbose_name='Gönderi')),
            ],
            options={
                'verbose_name': 'Kargo Takip',
                'verbose_name_plural': 'Kargo Takip Geçmişi',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CargoIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('api', 'API'), ('webhook', 'Webhook'), ('manual', 'Manuel')], default='api', max_length=50, verbose_name='Entegrasyon Türü')),
                ('webhook_url', models.URLField(blank=True, verbose_name='Webhook URL')),
                ('webhook_secret', models.CharField(blank=True, max_length=255, verbose_name='Webhook Gizli Anahtar')),
                ('auth_type', models.CharField(choices=[('bearer', 'Bearer Token'), ('basic', 'Basic Auth'), ('api_key', 'API Key'), ('oauth2', 'OAuth2')], default='api_key', max_length=20, verbose_name='Kimlik Doğrulama Türü')),
                ('test_mode', models.BooleanField(default=True, verbose_name='Test Modu')),
                ('test_api_key', models.CharField(blank=True, max_length=255, verbose_name='Test API Anahtarı')),
                ('test_api_secret', models.CharField(blank=True, max_length=255, verbose_name='Test API Gizli Anahtar')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Son Senkronizasyon')),
                ('total_shipments', models.IntegerField(default=0, verbose_name='Toplam Gönderi')),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Başarı Oranı (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('cargo_company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integration', to='core.cargocompany', verbose_name='Kargo Firması')),
            ],
            options={
                'verbose_name': 'Kargo Entegrasyonu',
                'verbose_name_plural': 'Kargo Entegrasyonları',
            },
        ),
    ]
