# Generated by Django 4.2.23 on 2025-12-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_cargo_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Şablon Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('width_mm', models.IntegerField(verbose_name='Genişlik (mm)')),
                ('height_mm', models.IntegerField(verbose_name='Yükseklik (mm)')),
                ('size_preset', models.CharField(choices=[('10x10', '10x10 cm'), ('10x15', '10x15 cm'), ('10x20', '10x20 cm'), ('15x10', '15x10 cm'), ('15x15', '15x15 cm'), ('a4', 'A4'), ('thermal_small', 'Termal Küçük (4x6 cm)'), ('thermal_large', 'Termal Büyük (8x12 cm)')], default='10x15', max_length=20, verbose_name='Boyut Ön Ayarı')),
                ('include_logo', models.BooleanField(default=True, verbose_name='Logo Dahil Et')),
                ('include_qr', models.BooleanField(default=True, verbose_name='QR Kod Dahil Et')),
                ('include_barcode', models.BooleanField(default=True, verbose_name='Barkod Dahil Et')),
                ('sender_info', models.BooleanField(default=True, verbose_name='Gönderen Bilgileri')),
                ('recipient_info', models.BooleanField(default=True, verbose_name='Alıcı Bilgileri')),
                ('package_info', models.BooleanField(default=True, verbose_name='Paket Bilgileri')),
                ('tracking_info', models.BooleanField(default=True, verbose_name='Takip Bilgileri')),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Arka Plan Rengi')),
                ('text_color', models.CharField(default='#000000', max_length=7, verbose_name='Metin Rengi')),
                ('border_color', models.CharField(default='#CCCCCC', max_length=7, verbose_name='Çerçeve Rengi')),
                ('font_size_small', models.IntegerField(default=8, verbose_name='Küçük Font Boyutu')),
                ('font_size_medium', models.IntegerField(default=12, verbose_name='Orta Font Boyutu')),
                ('font_size_large', models.IntegerField(default=16, verbose_name='Büyük Font Boyutu')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan Şablon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
            ],
            options={
                'verbose_name': 'Kargo Etiketi Şablonu',
                'verbose_name_plural': 'Kargo Etiketi Şablonları',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='cargoshipment',
            name='label_file',
            field=models.FileField(blank=True, null=True, upload_to='cargo_labels/', verbose_name='Etiket Dosyası'),
        ),
        migrations.AddField(
            model_name='cargoshipment',
            name='label_generated',
            field=models.BooleanField(default=False, verbose_name='Etiket Oluşturuldu'),
        ),
        migrations.AddField(
            model_name='cargoshipment',
            name='label_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Etiket Oluşturulma Tarihi'),
        ),
        migrations.AddField(
            model_name='cargoshipment',
            name='label_print_count',
            field=models.IntegerField(default=0, verbose_name='Etiket Baskı Sayısı'),
        ),
        migrations.AddField(
            model_name='cargoshipment',
            name='label_type',
            field=models.CharField(choices=[('thermal', 'Termal Etiket'), ('laser', 'Lazer Etiket'), ('pdf', 'PDF Etiket')], default='pdf', max_length=20, verbose_name='Etiket Türü'),
        ),
    ]
