# Generated by Django 4.2.23 on 2025-12-08 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_cargo_label_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoshipment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_shipments', to='core.invoice', verbose_name='Fatura'),
        ),
    ]
