# Generated by Django 4.2.23 on 2025-06-13 20:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mold.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('center', '0003_centermessage_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarMold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100, verbose_name='Hasta Adı')),
                ('patient_surname', models.CharField(max_length=100, verbose_name='Hasta Soyadı')),
                ('patient_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)], verbose_name='Yaş')),
                ('patient_gender', models.CharField(choices=[('M', 'Erkek'), ('F', 'Kadın')], max_length=1, verbose_name='Cinsiyet')),
                ('mold_type', models.CharField(choices=[('full', 'Tam Konka'), ('half', 'Yarım Konka'), ('skeleton', 'İskelet'), ('probe', 'Probe'), ('cic', 'CIC'), ('ite', 'ITE'), ('itc', 'ITC')], max_length=10, verbose_name='Kalıp Tipi')),
                ('vent_diameter', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Vent Çapı')),
                ('scan_file', models.FileField(upload_to='scans/', verbose_name='Tarama Dosyası')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('status', models.CharField(choices=[('waiting', 'Bekliyor'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('revision', 'Revizyon'), ('shipping', 'Kargoda'), ('delivered', 'Teslim Edildi')], default='waiting', max_length=20, verbose_name='Durum')),
                ('quality_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Kalite Puanı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='molds', to='center.center', verbose_name='Merkez')),
            ],
            options={
                'verbose_name': 'Kulak Kalıbı',
                'verbose_name_plural': 'Kulak Kalıpları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('mold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='mold.earmold', verbose_name='Kalıp')),
            ],
            options={
                'verbose_name': 'Revizyon',
                'verbose_name_plural': 'Revizyonlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_items', models.JSONField(verbose_name='Kontrol Listesi')),
                ('result', models.BooleanField(verbose_name='Sonuç')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Puan')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('mold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='mold.earmold', verbose_name='Kalıp')),
            ],
            options={
                'verbose_name': 'Kalite Kontrol',
                'verbose_name_plural': 'Kalite Kontroller',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModeledMold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='modeled/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['stl', 'obj', 'ply']), mold.validators.validate_file_size])),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('waiting', 'Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='waiting', max_length=20)),
                ('ear_mold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeled_files', to='mold.earmold')),
            ],
            options={
                'verbose_name': 'Modellenmiş Kalıp',
                'verbose_name_plural': 'Modellenmiş Kalıplar',
                'ordering': ['-created_at'],
            },
        ),
    ]
