# Generated by Django 4.2.23 on 2025-06-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mold', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='revision_type',
            field=models.CharField(choices=[('minor', 'Küçük Düzeltme'), ('major', 'Büyük Değişiklik'), ('remake', 'Yeniden Yapım')], default='minor', max_length=10, verbose_name='Revizyon Türü'),
        ),
    ]
