# Generated by Django 4.2.23 on 2025-06-18 18:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0006_alter_center_notification_preferences'),
        ('mold', '0002_revision_revision_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_type', models.CharField(choices=[('size_adjustment', 'Boyut Ayarlaması'), ('shape_modification', 'Şekil Değişikliği'), ('vent_adjustment', 'Vent Ayarlaması'), ('surface_improvement', 'Yüzey İyileştirmesi'), ('fitting_issue', 'Oturma Sorunu'), ('comfort_issue', 'Konfor Sorunu'), ('quality_issue', 'Kalite Sorunu'), ('remake', 'Yeniden Yapım'), ('other', 'Diğer')], max_length=20, verbose_name='Revizyon Türü')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Detaylı Açıklama')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('normal', 'Normal'), ('high', 'Yüksek'), ('urgent', 'Acil')], default='normal', max_length=10, verbose_name='Öncelik')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('accepted', 'Kabul Edildi'), ('rejected', 'Reddedildi'), ('in_progress', 'İşlemde'), ('completed', 'Tamamlandı')], default='pending', max_length=15, verbose_name='Durum')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notları')),
                ('producer_response', models.TextField(blank=True, verbose_name='Üretici Yanıtı')),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='revision_requests/', verbose_name='Referans Görsel')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='revision_requests/', verbose_name='Ek Dosya')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Çözülme Tarihi')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_requests', to='center.center', verbose_name='Merkez')),
                ('mold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_requests', to='mold.earmold', verbose_name='Kalıp')),
            ],
            options={
                'verbose_name': 'Revizyon Talebi',
                'verbose_name_plural': 'Revizyon Talepleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoldEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Kalite Puanı')),
                ('speed_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Hız Puanı')),
                ('communication_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='İletişim Puanı')),
                ('packaging_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Paketleme Puanı')),
                ('positive_feedback', models.TextField(blank=True, verbose_name='Olumlu Geri Bildirim')),
                ('negative_feedback', models.TextField(blank=True, verbose_name='Olumsuz Geri Bildirim')),
                ('suggestions', models.TextField(blank=True, verbose_name='Öneriler')),
                ('overall_satisfaction', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Genel Memnuniyet')),
                ('would_recommend', models.BooleanField(default=True, verbose_name='Tavsiye Eder misiniz?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Değerlendirme Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mold_evaluations', to='center.center', verbose_name='Merkez')),
                ('mold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='mold.earmold', verbose_name='Kalıp')),
            ],
            options={
                'verbose_name': 'Kalıp Değerlendirmesi',
                'verbose_name_plural': 'Kalıp Değerlendirmeleri',
                'ordering': ['-created_at'],
                'unique_together': {('mold', 'center')},
            },
        ),
    ]
