# Generated by Django 4.2.23 on 2025-06-18 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mold', '0003_revisionrequest_moldevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionrequest',
            name='modeled_mold',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='revision_requests', to='mold.modeledmold', verbose_name='Kalıp Dosyası'),
            preserve_default=False,
        ),
    ]
