# Generated by Django 4.2.23 on 2025-06-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mold', '0004_revisionrequest_modeled_mold'),
    ]

    operations = [
        migrations.AddField(
            model_name='earmold',
            name='carrier_company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kargo Firması'),
        ),
        migrations.AddField(
            model_name='earmold',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True, verbose_name='Tahmini Teslimat Tarihi'),
        ),
        migrations.AddField(
            model_name='earmold',
            name='is_physical_shipment',
            field=models.BooleanField(default=False, help_text='Dijital dosya yerine fiziksel kalıp gönderilecek', verbose_name='Fiziksel Kalıp Gönderimi'),
        ),
        migrations.AddField(
            model_name='earmold',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'Yüksek'), ('urgent', 'Acil')], default='normal', max_length=20, verbose_name='Öncelik'),
        ),
        migrations.AddField(
            model_name='earmold',
            name='shipment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kargo Gönderim Tarihi'),
        ),
        migrations.AddField(
            model_name='earmold',
            name='shipment_notes',
            field=models.TextField(blank=True, help_text='Kargo ile ilgili özel talimatlar', verbose_name='Kargo Notları'),
        ),
        migrations.AddField(
            model_name='earmold',
            name='shipment_status',
            field=models.CharField(choices=[('not_shipped', 'Henüz Gönderilmedi'), ('shipped', 'Kargoya Verildi'), ('in_transit', 'Yolda'), ('delivered_to_producer', 'Üreticiye Teslim Edildi'), ('returned', 'İade Edildi')], default='not_shipped', max_length=30, verbose_name='Kargo Durumu'),
        ),
        migrations.AddField(
            model_name='earmold',
            name='special_instructions',
            field=models.TextField(blank=True, verbose_name='Özel Talimatlar'),
        ),
        migrations.AddField(
            model_name='earmold',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kargo Takip Numarası'),
        ),
        migrations.AlterField(
            model_name='earmold',
            name='scan_file',
            field=models.FileField(blank=True, null=True, upload_to='scans/', verbose_name='Tarama Dosyası'),
        ),
    ]
