# Generated by Django 4.2.23 on 2025-06-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mold', '0005_add_physical_shipment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earmold',
            name='status',
            field=models.CharField(choices=[('waiting', 'Bekliyor'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('revision', 'Revizyon'), ('rejected', 'Reddedildi'), ('shipping', 'Kargoda'), ('delivered', 'Teslim Edildi')], default='waiting', max_length=20, verbose_name='Durum'),
        ),
    ]
