# Generated by Django 4.2.23 on 2025-06-27 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mold', '0006_alter_earmold_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revisionrequest',
            name='mold',
        ),
    ]
