# Generated by Django 4.2.23 on 2025-07-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mold', '0007_remove_revisionrequest_mold'),
    ]

    operations = [
        migrations.AddField(
            model_name='earmold',
            name='ear_side',
            field=models.CharField(choices=[('right', 'Sağ'), ('left', 'Sol')], default='right', max_length=5, verbose_name='Kulak Yönü'),
        ),
    ]
