# Generated by Django 4.2.23 on 2025-07-02 19:51

import django.core.validators
from django.db import migrations, models
import mold.models


class Migration(migrations.Migration):

    dependencies = [
        ('mold', '0008_earmold_ear_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earmold',
            name='scan_file',
            field=models.FileField(blank=True, help_text='STL, OBJ, PLY, ZIP veya RAR formatında tarama dosyası yükleyin (Maks. 100MB)', null=True, upload_to='scans/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['stl', 'obj', 'ply', 'zip', 'rar'], message='Sadece STL, OBJ, PLY, ZIP ve RAR dosyaları yüklenebilir.'), mold.models.validate_scan_file_size], verbose_name='Tarama Dosyası'),
        ),
    ]
