# Generated by Django 4.2.23 on 2025-07-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mold', '0009_alter_earmold_scan_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionrequest',
            name='admin_response_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Admin Yanıt Süresi'),
        ),
        migrations.AddField(
            model_name='revisionrequest',
            name='admin_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Admin İnceleme Tarihi'),
        ),
        migrations.AddField(
            model_name='revisionrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi'),
        ),
        migrations.AddField(
            model_name='revisionrequest',
            name='expected_delivery',
            field=models.DateField(blank=True, null=True, verbose_name='Beklenen Teslim Tarihi'),
        ),
        migrations.AddField(
            model_name='revisionrequest',
            name='process_steps',
            field=models.JSONField(blank=True, default=list, verbose_name='Süreç Adımları'),
        ),
        migrations.AddField(
            model_name='revisionrequest',
            name='producer_response_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Üretici Yanıt Süresi'),
        ),
        migrations.AddField(
            model_name='revisionrequest',
            name='producer_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Üretici İnceleme Tarihi'),
        ),
        migrations.AddField(
            model_name='revisionrequest',
            name='quality_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kalite Kontrol Tarihi'),
        ),
        migrations.AddField(
            model_name='revisionrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Red Nedeni'),
        ),
        migrations.AddField(
            model_name='revisionrequest',
            name='total_days',
            field=models.IntegerField(default=0, verbose_name='Toplam Gün'),
        ),
        migrations.AddField(
            model_name='revisionrequest',
            name='work_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='İş Başlama Tarihi'),
        ),
        migrations.AlterField(
            model_name='earmold',
            name='carrier_company',
            field=models.CharField(blank=True, choices=[('aras', 'Aras Kargo'), ('yurtici', 'Yurtiçi Kargo'), ('mng', 'MNG Kargo'), ('ptt', 'PTT Kargo'), ('ups', 'UPS'), ('dhl', 'DHL'), ('fedex', 'FedEx'), ('other', 'Diğer')], max_length=20, null=True, verbose_name='Kargo Firması'),
        ),
        migrations.AlterField(
            model_name='earmold',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal (5-7 iş günü)'), ('high', 'Yüksek (3-4 iş günü)'), ('urgent', 'Acil (1-2 iş günü)')], default='normal', max_length=20, verbose_name='Öncelik'),
        ),
        migrations.AlterField(
            model_name='revisionrequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Düşük (7-10 iş günü)'), ('normal', 'Normal (5-7 iş günü)'), ('high', 'Yüksek (3-4 iş günü)'), ('urgent', 'Acil (1-2 iş günü)')], default='normal', max_length=10, verbose_name='Öncelik'),
        ),
        migrations.AlterField(
            model_name='revisionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('admin_review', 'Admin İncelemesi'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('producer_review', 'Üretici İncelemesi'), ('accepted', 'Kabul Edildi'), ('producer_rejected', 'Üretici Reddetti'), ('in_progress', 'İşlemde'), ('quality_check', 'Kalite Kontrol'), ('ready_for_delivery', 'Teslimat Hazır'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum'),
        ),
        migrations.AddIndex(
            model_name='revisionrequest',
            index=models.Index(fields=['status', 'priority'], name='mold_revisi_status_5e3e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='revisionrequest',
            index=models.Index(fields=['created_at', 'status'], name='mold_revisi_created_99bac1_idx'),
        ),
    ]
