# Generated by Django 4.2.23 on 2025-07-05 15:07

import django.core.validators
from django.db import migrations, models
import mold.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mold', '0010_revision_process_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionrequest',
            name='revised_file',
            field=models.FileField(blank=True, null=True, upload_to='revised/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['stl', 'obj', 'ply', '3mf', 'amf']), mold.validators.validate_file_size], verbose_name='Revize Edilmiş Dosya'),
        ),
        migrations.AddField(
            model_name='revisionrequest',
            name='revision_notes',
            field=models.TextField(blank=True, help_text='Üretici tarafından yapılan değişiklikler hakkında notlar', verbose_name='Revizyon Notları'),
        ),
    ]
