# Generated by Django 4.2.23 on 2025-07-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mold', '0011_revisionrequest_revised_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='earmold',
            name='file_format',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Dosya Formatı'),
        ),
        migrations.AddField(
            model_name='earmold',
            name='model_complexity',
            field=models.CharField(blank=True, choices=[('low', 'Düşük (< 10K polygon)'), ('medium', 'Orta (10K-50K polygon)'), ('high', 'Yüksek (> 50K polygon)')], max_length=20, null=True, verbose_name='Model Karmaşıklığı'),
        ),
        migrations.AddField(
            model_name='earmold',
            name='polygon_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Polygon Sayısı'),
        ),
        migrations.AddField(
            model_name='earmold',
            name='scan_thumbnail',
            field=models.ImageField(blank=True, help_text='3D tarama dosyasının küçük önizleme görseli', null=True, upload_to='thumbnails/scans/', verbose_name='Tarama Önizleme'),
        ),
        migrations.AddField(
            model_name='earmold',
            name='vertex_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vertex Sayısı'),
        ),
        migrations.AddField(
            model_name='modeledmold',
            name='file_format',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Dosya Formatı'),
        ),
        migrations.AddField(
            model_name='modeledmold',
            name='model_complexity',
            field=models.CharField(blank=True, choices=[('low', 'Düşük (< 10K polygon)'), ('medium', 'Orta (10K-50K polygon)'), ('high', 'Yüksek (> 50K polygon)')], max_length=20, null=True, verbose_name='Model Karmaşıklığı'),
        ),
        migrations.AddField(
            model_name='modeledmold',
            name='model_thumbnail',
            field=models.ImageField(blank=True, help_text='3D model dosyasının küçük önizleme görseli', null=True, upload_to='thumbnails/models/', verbose_name='Model Önizleme'),
        ),
        migrations.AddField(
            model_name='modeledmold',
            name='polygon_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Polygon Sayısı'),
        ),
        migrations.AddField(
            model_name='modeledmold',
            name='render_settings',
            field=models.JSONField(blank=True, default=dict, help_text='3D görüntüleyici için kamera pozisyonu, ışık ayarları vb.', verbose_name='3D Render Ayarları'),
        ),
        migrations.AddField(
            model_name='modeledmold',
            name='vertex_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vertex Sayısı'),
        ),
        migrations.AlterField(
            model_name='modeledmold',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='revisionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('producer_review', 'Üretici İncelemesi'), ('accepted', 'Kabul Edildi'), ('producer_rejected', 'Üretici Reddetti'), ('in_progress', 'İşlemde'), ('quality_check', 'Kalite Kontrol'), ('ready_for_delivery', 'Teslimat Hazır'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum'),
        ),
    ]
