# Generated by Django 4.2.23 on 2025-10-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mold', '0012_earmold_file_format_earmold_model_complexity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earmold',
            name='status',
            field=models.CharField(choices=[('waiting', 'Bekliyor'), ('shipped_to_producer', 'Üreticiye Gönderildi'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('revision', 'Revizyon'), ('rejected', 'Reddedildi'), ('shipped_to_center', 'Merkeze Gönderildi'), ('delivered', 'Teslim Edildi')], default='waiting', max_length=20, verbose_name='Durum'),
        ),
    ]
