# Generated by Django 4.2.23 on 2025-10-10 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0007_delete_centermessage'),
        ('mold', '0013_alter_earmold_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='earmold',
            name='delivery_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Teslimat Onay Tarihi'),
        ),
        migrations.AddField(
            model_name='earmold',
            name='delivery_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_deliveries', to='center.center', verbose_name='Teslimatı Onaylayan'),
        ),
        migrations.AddField(
            model_name='earmold',
            name='delivery_notes',
            field=models.TextField(blank=True, help_text='Teslimat onayı sırasında eklenen notlar', verbose_name='Teslimat Notları'),
        ),
        migrations.AlterField(
            model_name='earmold',
            name='status',
            field=models.CharField(choices=[('waiting', 'Bekliyor'), ('shipped_to_producer', 'Üreticiye Gönderildi'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('revision', 'Revizyon'), ('rejected', 'Reddedildi'), ('shipped_to_center', 'Merkeze Gönderildi'), ('delivered_pending_approval', 'Teslimat Onayı Bekleniyor'), ('delivered', 'Teslim Edildi ve Onaylandı')], default='waiting', max_length=30, verbose_name='Durum'),
        ),
    ]
