# Generated by Django 4.2.23 on 2025-11-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mold', '0014_add_delivery_approval_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='earmold',
            name='digital_modeling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bu kalıp için kullanılan 3D modelleme fiyatı', max_digits=10, null=True, verbose_name='3D Modelleme Fiyatı (TL)'),
        ),
        migrations.AddField(
            model_name='earmold',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bu kalıp için kullanılan birim fiyat (paket hakkından kullanıldıysa 0)', max_digits=10, null=True, verbose_name='Birim Fiyat (TL)'),
        ),
    ]
