# Generated by Django 5.0.2 on 2025-06-11 09:17

import django.core.validators
import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Merkez Adı')),
                ('address', models.TextField(verbose_name='Adres')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('mold_limit', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kalıp Limiti')),
                ('notification_preferences', multiselectfield.db.fields.MultiSelectField(choices=[('new_order', 'Yeni Sipariş'), ('revision', 'Revizyon'), ('completed', 'Tamamlanan Sipariş'), ('urgent', 'Acil Durum'), ('system', 'Sistem Bildirimleri')], default=['system'], max_length=42, verbose_name='Bildirim Tercihleri')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='center', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Merkez',
                'verbose_name_plural': 'Merkezler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CenterMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderilme Tarihi')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='center.center', verbose_name='Alıcı')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='center.center', verbose_name='Gönderen')),
            ],
            options={
                'verbose_name': 'Merkez Mesajı',
                'verbose_name_plural': 'Merkez Mesajları',
                'ordering': ['-created_at'],
            },
        ),
    ]
