# Generated by Django 4.2.23 on 2025-06-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_center_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='centermessage',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Arşivlendi'),
        ),
    ]
