# Generated by Django 4.2.23 on 2025-06-14 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_centermessage_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='monthly_limit',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Aylık Kalıp Limiti'),
        ),
    ]
