# Generated by Django 4.2.23 on 2025-06-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0005_update_monthly_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='notification_preferences',
            field=models.CharField(default='system', help_text='Virgülle ayrılmış bildirim türleri', max_length=200, verbose_name='Bildirim Tercihleri'),
        ),
    ]
