# Generated by Django 4.2.23 on 2025-06-27 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0006_alter_center_notification_preferences'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CenterMessage',
        ),
    ]
