# Generated by Django 4.2.23 on 2025-12-12 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0007_delete_centermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_company_name', models.CharField(max_length=200, verbose_name='Alıcı Firma Adı')),
                ('recipient_address', models.TextField(verbose_name='Alıcı Adres')),
                ('recipient_city', models.CharField(blank=True, max_length=100, verbose_name='Alıcı Şehir')),
                ('recipient_phone', models.CharField(blank=True, max_length=20, verbose_name='Alıcı Telefon')),
                ('issue_date', models.DateField(verbose_name='Tarih')),
                ('note_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='İrsaliye No')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Taslak')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_notes', to='center.center', verbose_name='İşitme Merkezi')),
            ],
            options={
                'verbose_name': 'Sevk İrsaliyesi',
                'verbose_name_plural': 'Sevk İrsaliyeleri',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Firma Adı')),
                ('address', models.TextField(verbose_name='Adres')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Şehir')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='Vergi No')),
                ('tax_office', models.CharField(blank=True, max_length=100, verbose_name='Vergi Dairesi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='center.center', verbose_name='İşitme Merkezi')),
            ],
            options={
                'verbose_name': 'Alıcı',
                'verbose_name_plural': 'Alıcılar',
                'ordering': ['company_name'],
                'unique_together': {('center', 'company_name')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinsi', models.CharField(max_length=200, verbose_name='Cinsi')),
                ('miktar', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Miktar')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Birim Fiyat')),
                ('tutari', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tutarı')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('delivery_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_items', to='center.deliverynote', verbose_name='Sevk İrsaliyesi')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to='center.recipient', verbose_name='Alıcı'),
        ),
    ]
